import type { Locale } from '../../i18n/locales';
import type { ToolContent } from '../types';

const uiEn = {
  birthDate: 'Date of birth',
  referenceDate: 'As of date',
  referenceHint: 'Defaults to today — change it to check an age on any other date.',
  resetToday: 'Reset to today',
  autosaved: 'Your birth date is saved in this browser',
  invalidDate: 'Choose a valid calendar date.',
  futureBirth: 'The date of birth must be on or before the "as of" date.',
  internationalAge: 'International age (만 나이)',
  ageUnitSingular: ' year old',
  ageUnitPlural: ' years old',
  exactAge: 'Exact age',
  yearUnit: 'y',
  monthUnit: 'm',
  dayUnit: 'd',
  countingAge: 'Korean counting age (세는 나이)',
  yearAge: 'Year age (연 나이)',
  zodiacAnimal: 'Chinese zodiac',
  zodiacBoundaryNotice:
    'Born in January or early February? Your zodiac animal may differ by one year depending on the Lunar New Year or 입춘 — see the FAQ below.',
  starSign: 'Star sign',
  daysLived: 'Days lived',
  daysLivedUnit: ' day',
  nextBirthday: 'Next birthday',
  nextBirthdayToday: 'Today is the birthday!',
  inDaySingular: 'in {n} day',
  inDaysPlural: 'in {n} days',
  copy: 'Copy summary',
  copied: 'Copied',
  summary:
    'Born {birth} ({weekday}). As of {reference}: {intlAge} years old (international age), {countingAge} by Korean counting age, {yearAge} by year age — {animal}, {sign}.',
  animalRat: 'Rat',
  animalOx: 'Ox',
  animalTiger: 'Tiger',
  animalRabbit: 'Rabbit',
  animalDragon: 'Dragon',
  animalSnake: 'Snake',
  animalHorse: 'Horse',
  animalGoat: 'Goat',
  animalMonkey: 'Monkey',
  animalRooster: 'Rooster',
  animalDog: 'Dog',
  animalPig: 'Pig',
  signAries: 'Aries',
  signTaurus: 'Taurus',
  signGemini: 'Gemini',
  signCancer: 'Cancer',
  signLeo: 'Leo',
  signVirgo: 'Virgo',
  signLibra: 'Libra',
  signScorpio: 'Scorpio',
  signSagittarius: 'Sagittarius',
  signCapricorn: 'Capricorn',
  signAquarius: 'Aquarius',
  signPisces: 'Pisces',
};
export type UI = typeof uiEn;

export const content: Record<Locale, ToolContent<UI>> = {
  en: {
    title: 'Age Calculator — International, Korean Age, Zodiac',
    description:
      'Get your exact age, Korean counting age and year age, Chinese zodiac animal and star sign from a date of birth — updates instantly in your browser, no ads.',
    h1: 'Age Calculator',
    tagline: 'Your exact age, Korean age conventions, zodiac animal and star sign — all from one date of birth.',
    name: 'Age Calculator',
    keywords: [
      'age calculator',
      'how old am i',
      'korean age calculator',
      'international age',
      'chinese zodiac calculator',
      'what is my zodiac sign',
      'years months days calculator',
    ],
    howTo: [
      'Enter your date of birth.',
      'Leave "As of date" on today, or change it to check an age on any other date (e.g. a school enrollment or contract date).',
      'Read your international age (만 나이), exact years/months/days, Korean counting age, and year age at a glance.',
      'Scroll down to see your Chinese zodiac animal, star sign, total days lived, and the countdown to your next birthday.',
      'Copy the one-line summary to paste anywhere — your birth date stays saved in this browser only.',
    ],
    sections: [
      {
        heading: 'Three different "ages" in Korea, and why they give different numbers',
        body: 'South Korea used three age systems side by side until the "Age Unification Act" (만 나이 통일법) took effect on June 28, 2023, after which 만 나이 (international age) became the default in law, contracts and official documents unless a rule says otherwise. 만 나이 only increases on your actual birthday, exactly like most of the world. 세는 나이 (counting age) treats your birth year as age 1 and adds one year on every January 1st — so a baby born on December 31 turns "2" the very next day, even though no real year has passed. 연 나이 (year age) is simpler: current year minus birth year, used by specific statutes such as the Military Service Act and the Juvenile Protection Act, and it also changes every January 1st rather than on the birthday. This calculator shows all three side by side so you can see exactly how far apart they are for your own birth date.',
      },
      {
        heading: 'How the Chinese zodiac animal and star sign are worked out',
        body: 'The Chinese zodiac repeats on a fixed 12-year cycle; this calculator anchors it to verified recent years (2020 Rat, 2024 Dragon, 2025 Snake, 2026 Horse) and counts by the plain solar calendar year, which matches how most people casually say "a 2024 baby is a Dragon." Be aware this is a simplification: people born in January or early February sometimes use a different cutoff — either the Lunar New Year or, in traditional 사주 (Korean fortune-telling) practice, the solar term 입춘 (around February 3–5) — so a birth in that narrow window can be one animal year off from the plain-calendar result shown here. The star sign uses the standard Western tropical date ranges (for example Aries runs March 21 to April 19), which do not depend on the lunar calendar and have no such ambiguity.',
      },
      {
        heading: 'Days lived and the next-birthday countdown',
        body: 'The "days lived" count treats your date of birth itself as day 1 — the same convention used for a Korean baby\'s 100th-day (백일) celebration, so someone born January 1 reaches their 100th day on April 10 in a common year. The next-birthday countdown finds the nearest upcoming date that matches your birth month and day; if you were born on February 29, it lands on February 28 in any year that is not a leap year, matching how most calendar apps handle it.',
      },
    ],
    faq: [
      {
        q: 'What is 만 나이 (international age) and when did it become official in Korea?',
        a: 'It is age counted from 0 at birth, adding one year on each birthday — the same system used in most countries. South Korea\'s "Age Unification Act" made 만 나이 the default for laws, contracts and official documents starting June 28, 2023, replacing mixed use of 세는 나이 and 연 나이 in everyday life.',
      },
      {
        q: 'Why does 세는 나이 (Korean counting age) make a newborn turn 2 so fast?',
        a: 'Counting age starts at 1 in your birth year and adds one year on every January 1st, not on your birthday. A baby born December 31 is "1" that day and "2" on January 1 — a one-day gap that represents zero real years lived, which is exactly the quirk this calculator\'s Korean counting age stat shows.',
      },
      {
        q: 'What is 연 나이 (year age) used for?',
        a: 'Year age is simply the current year minus your birth year. It is the age basis written into specific Korean statutes such as the Military Service Act and the Juvenile Protection Act, and like counting age it changes every January 1st rather than on your birthday.',
      },
      {
        q: 'Is the Chinese zodiac animal based on the lunar calendar or the solar calendar?',
        a: 'This calculator uses the plain solar calendar year, which matches everyday usage (a 2024 baby is a Dragon). If you were born in January or early February, note that the Lunar New Year or the solar term 입춘 (around February 3–5) is sometimes used instead as the cutoff, which can shift the result by one animal for that narrow window.',
      },
      {
        q: 'How is my star sign determined?',
        a: 'From the standard Western tropical date ranges based on your birth month and day alone — for example, anyone born March 21 to April 19 is Aries. These ranges do not depend on the lunar calendar, so there is no ambiguity like with the Chinese zodiac.',
      },
      {
        q: 'How many days old am I, and when is my 100th day (백일)?',
        a: "Your date of birth counts as day 1, so someone born January 1 reaches day 100 on April 10 in a common (non-leap) year. Some hospitals count the birth date as day 0 for medical schedules like vaccinations, so follow your clinic's own count for those specific dates.",
      },
      {
        q: 'Is my date of birth sent to a server?',
        a: "No. Every calculation runs in your browser with plain JavaScript, and your birth date is saved only in this browser's local storage so it is there next time — never on a server or in an account.",
      },
    ],
    ui: uiEn,
  },
  ko: {
    title: '나이 계산기 — 만 나이·세는 나이·연 나이·띠·별자리',
    description:
      '생년월일 하나로 만 나이, 세는 나이, 연 나이, 띠, 별자리를 입력하는 즉시 계산합니다. 버튼 클릭 없이 바로 업데이트되고, 광고와 서버 전송이 없습니다.',
    h1: '나이 계산기',
    tagline: '생년월일 하나로 만 나이·세는 나이·연 나이와 띠·별자리까지 한 번에 확인하세요.',
    name: '나이 계산기',
    keywords: ['나이 계산기', '만 나이 계산기', '내 나이', '한국 나이 계산', '띠 계산기', '별자리 계산기', '만나이'],
    howTo: [
      '생년월일을 입력하세요.',
      '"기준일"은 오늘로 자동 설정되며, 특정 날짜(입학일, 계약일 등) 기준 나이를 보려면 직접 바꾸면 됩니다.',
      '만 나이, 정확한 연·월·일, 세는 나이, 연 나이가 바로 화면에 나타납니다.',
      '아래에서 띠, 별자리, 태어난 지 며칠째인지, 다음 생일까지 남은 날도 확인하세요.',
      '한 줄 요약을 복사해 바로 공유할 수 있고, 생년월일은 이 브라우저에만 저장됩니다.',
    ],
    sections: [
      {
        heading: '만 나이·세는 나이·연 나이, 숫자가 다른 이유',
        body: '2023년 6월 28일 "만 나이 통일법" 시행 전까지 한국에서는 세 가지 나이 셈법이 혼용됐습니다. 이제는 법령·계약서·공문서에서 별도 규정이 없으면 만 나이를 기본으로 씁니다. 만 나이는 전 세계 대부분이 쓰는 방식으로, 생일이 지나야만 한 살을 더 먹습니다. 세는 나이(한국식 나이)는 태어난 해를 1살로 보고 생일과 무관하게 매년 1월 1일마다 한 살씩 더해, 12월 31일에 태어난 아기는 바로 다음 날인 1월 1일에 "두 살"이 됩니다. 연 나이는 병역법·청소년보호법 등 특정 법령에서 쓰는 방식으로, 단순히 "올해 연도 − 출생 연도"로 계산하며 역시 생일이 아니라 1월 1일마다 바뀝니다. 이 계산기는 세 나이를 한 화면에 동시에 보여줘 내 생년월일로는 그 차이가 정확히 며칠·몇 달인지 바로 확인할 수 있습니다.',
      },
      {
        heading: '띠와 별자리는 어떻게 계산하나요',
        body: '띠는 12년 주기로 반복되며, 이 계산기는 확인된 최근 연도(2020년 쥐띠, 2024년 용띠, 2025년 뱀띠, 2026년 말띠)를 기준으로 양력 연도 그대로 계산합니다. "2024년생은 용띠"라고 말하는 일상적인 쓰임과 같은 방식입니다. 다만 1월과 2월 초에 태어났다면 주의가 필요합니다. 일부는 음력 설날을 기준으로 띠가 바뀐다고 보고, 사주명리학 전통에서는 절기인 입춘(2월 3~5일 무렵)을 기준으로 삼기도 해서, 그 짧은 기간에 태어난 경우 이 계산기가 보여주는 양력 연도 기준 띠와 한 해 차이가 날 수 있습니다. 별자리는 음력과 무관하게 태어난 월·일만으로 정해지는 서양 점성술의 표준 날짜 구간(예: 양자리는 3월 21일~4월 19일)을 그대로 쓰기 때문에 이런 모호함이 없습니다.',
      },
      {
        heading: '태어난 지 며칠째인지, 다음 생일까지 남은 날',
        body: '"태어난 지 며칠째"는 태어난 날 자체를 1일로 세는 방식을 씁니다. 아기 백일(100일) 잔치를 계산할 때와 같은 방식으로, 평년(윤년이 아닌 해) 1월 1일에 태어난 아기는 4월 10일이 백일입니다. 다음 생일까지 남은 날은 생년월일의 월·일과 같은 가장 가까운 미래 날짜를 찾아 계산하며, 2월 29일에 태어났다면 윤년이 아닌 해에는 대부분의 캘린더 앱과 같은 방식으로 2월 28일을 생일로 봅니다.',
      },
    ],
    faq: [
      {
        q: '만 나이는 언제부터 공식적으로 쓰이게 됐나요?',
        a: '태어날 때 0살로 시작해 생일이 지날 때마다 한 살씩 더하는, 세계 대부분이 쓰는 나이 셈법입니다. 2023년 6월 28일 "만 나이 통일법" 시행으로 법령·계약·공문서에서는 특별한 규정이 없으면 만 나이를 기본으로 쓰도록 통일됐습니다.',
      },
      {
        q: '세는 나이로는 왜 태어난 지 얼마 안 된 아기가 두 살이 되나요?',
        a: '세는 나이는 태어난 해를 1살로 보고 생일이 아니라 매년 1월 1일마다 한 살씩 더하기 때문입니다. 12월 31일에 태어난 아기는 그날 "한 살", 다음 날인 1월 1일에 "두 살"이 되는데, 실제로는 하루밖에 지나지 않았습니다. 이 계산기의 세는 나이 항목이 바로 이 차이를 보여줍니다.',
      },
      {
        q: '연 나이는 어디에 쓰이나요?',
        a: '연 나이는 올해 연도에서 출생 연도를 그냥 뺀 값입니다. 병역법, 청소년보호법 등 특정 법령에서 기준으로 쓰며, 세는 나이와 마찬가지로 생일이 아니라 매년 1월 1일마다 바뀝니다.',
      },
      {
        q: '띠는 음력 기준인가요, 양력 기준인가요?',
        a: '이 계산기는 "2024년생은 용띠"처럼 일상에서 흔히 쓰는 방식대로 양력 연도를 그대로 씁니다. 다만 1월~2월 초 출생자는 음력 설날이나 사주명리학의 입춘(2월 3~5일 무렵)을 기준으로 보면 한 해 다른 띠가 나올 수 있다는 점을 참고하세요.',
      },
      {
        q: '별자리는 어떻게 정해지나요?',
        a: '태어난 월과 일만으로 정해지는 서양 점성술의 표준 날짜 구간을 씁니다. 예를 들어 3월 21일부터 4월 19일 사이에 태어났다면 양자리이며, 음력과는 무관해 띠와 같은 모호함이 없습니다.',
      },
      {
        q: '태어난 지 며칠째인지, 백일은 언제인지 어떻게 계산하나요?',
        a: '태어난 날을 1일로 세므로, 평년 1월 1일에 태어났다면 100일째인 백일은 4월 10일입니다. 예방접종 등 병원 일정은 출생일을 0일로 세는 경우가 있어 해당 일정은 병원 안내를 따로 확인하세요.',
      },
      {
        q: '입력한 생년월일이 서버로 전송되나요?',
        a: '아니요. 모든 계산은 브라우저 안에서 자바스크립트로 처리되고, 생년월일은 이 브라우저의 로컬 저장소에만 남아 다시 열어도 유지되며 서버나 계정에는 전혀 저장되지 않습니다.',
      },
    ],
    ui: {
      birthDate: '생년월일',
      referenceDate: '기준일',
      referenceHint: '오늘로 기본 설정되며, 다른 날짜 기준으로 보려면 직접 바꾸세요.',
      resetToday: '오늘로 초기화',
      autosaved: '생년월일은 이 브라우저에 저장됩니다',
      invalidDate: '올바른 날짜를 선택하세요.',
      futureBirth: '생년월일은 기준일보다 이전이거나 같아야 합니다.',
      internationalAge: '만 나이',
      ageUnitSingular: '세',
      ageUnitPlural: '세',
      exactAge: '정확한 만 나이',
      yearUnit: '년',
      monthUnit: '개월',
      dayUnit: '일',
      countingAge: '세는 나이',
      yearAge: '연 나이',
      zodiacAnimal: '띠',
      zodiacBoundaryNotice:
        '1월~2월 5일경 출생이면 음력 설날·입춘 기준으로 띠가 다를 수 있어요. 아래 FAQ를 확인하세요.',
      starSign: '별자리',
      daysLived: '태어난 지',
      daysLivedUnit: '일째',
      nextBirthday: '다음 생일',
      nextBirthdayToday: '오늘이 생일이에요!',
      inDaySingular: '{n}일 후',
      inDaysPlural: '{n}일 후',
      copy: '요약 복사',
      copied: '복사됨',
      summary:
        '{birth}({weekday}) 출생. {reference} 기준 만 {intlAge}세, 세는 나이 {countingAge}세, 연 나이 {yearAge}세 — {animal}, {sign}.',
      animalRat: '쥐띠',
      animalOx: '소띠',
      animalTiger: '호랑이띠',
      animalRabbit: '토끼띠',
      animalDragon: '용띠',
      animalSnake: '뱀띠',
      animalHorse: '말띠',
      animalGoat: '양띠',
      animalMonkey: '원숭이띠',
      animalRooster: '닭띠',
      animalDog: '개띠',
      animalPig: '돼지띠',
      signAries: '양자리',
      signTaurus: '황소자리',
      signGemini: '쌍둥이자리',
      signCancer: '게자리',
      signLeo: '사자자리',
      signVirgo: '처녀자리',
      signLibra: '천칭자리',
      signScorpio: '전갈자리',
      signSagittarius: '사수자리',
      signCapricorn: '염소자리',
      signAquarius: '물병자리',
      signPisces: '물고기자리',
    },
  },
};
