import type { Locale } from '../../i18n/locales';
import type { ToolContent } from '../types';

const uiEn = {
  focus: 'Focus',
  shortBreak: 'Short break',
  longBreak: 'Long break',
  phase: 'Session type',
  start: 'Start',
  pause: 'Pause',
  resume: 'Resume',
  reset: 'Reset',
  skip: 'Skip',
  completed: 'Session complete — the next session is ready.',
  tasks: 'Task list',
  tasksHint: 'Select one task before you focus.',
  taskPlaceholder: 'What will you focus on?',
  addTask: 'Add',
  noTasks: 'Add a task to attach it to completed focus sessions.',
  selectTask: 'Select {task}',
  select: 'Select',
  selected: 'Selected',
  done: 'Done',
  reopen: 'Reopen',
  removeTask: 'Remove {task}',
  remove: 'Remove',
  today: 'Focus sessions today',
  round: 'Next focus round',
  notifications: 'Browser notifications',
  notificationHint: 'Your browser asks permission only when you turn this on.',
  notificationTitle: 'Pomodoro timer',
  notificationBody: 'Session complete. Next: {phase}.',
  settings: 'Session settings',
  settingsHint: 'Changing a setting resets the current timer.',
  focusMinutes: 'Focus (minutes)',
  shortBreakMinutes: 'Short break (minutes)',
  longBreakMinutes: 'Long break (minutes)',
  rounds: 'Focus sessions before long break',
  sessionLog: 'Focus session log',
  sessionLogHint: 'The newest 100 completed focus sessions stay in this browser.',
  noSessions: 'Complete a focus session to add the first record.',
  untitledTask: 'Untitled focus session',
  startPause: 'Start / pause',
};
export type UI = typeof uiEn;

export const content: Record<Locale, ToolContent<UI>> = {
  en: {
    title: 'Pomodoro Timer — Tasks, Session Log and Alerts',
    description:
      'Run a free Pomodoro timer with an editable task list, local focus-session log and optional browser alerts. No account, ads or data leaving your browser.',
    h1: 'Pomodoro Timer',
    tagline: 'Focus on one selected task, keep a local session record, and get optional alerts without signing in.',
    name: 'Pomodoro Timer',
    keywords: [
      'pomodoro timer',
      'focus timer',
      'study timer',
      '25 minute timer',
      'work break timer',
      'pomodoro technique',
    ],
    howTo: [
      'Add the task you want to focus on, then select it with the round button.',
      'Press Start or Space to begin the default 25-minute focus session.',
      'Take the prepared 5-minute short break when focus finishes; every fourth focus session prepares a 15-minute long break.',
      'Open Session settings before starting to use a different focus length or round count.',
      'Review the task-linked focus-session log, which remains only in this browser.',
    ],
    sections: [
      {
        heading: 'The classic Pomodoro rhythm is 25 / 5, then a longer break',
        body: 'The familiar Pomodoro pattern is 25 minutes of focused work followed by a 5-minute break. After four completed focus intervals, it uses a longer break; 15 minutes is a common starting setting. Those durations are a method, not a measurement of productivity, so this timer lets you choose 1–180 minutes for every interval and 1–12 focus sessions before the long break. Change the rhythm before starting because changing settings resets the current countdown.',
      },
      {
        heading: 'Completed focus sessions stay on this device',
        body: 'When a focus interval reaches zero, this tool stores its completion time and the selected task name in this browser’s local storage. It keeps the newest 100 focus records, and the “today” count compares the recorded local calendar date with the date on your device. There is no account, server request or third-party tracker behind that record. Clearing site data or using a different browser removes or separates the local history.',
      },
      {
        heading: 'Why the countdown does not drift in a background tab',
        body: 'The timer saves the clock time at which the interval should end, then subtracts the current clock time to find what remains. It does not add one second for each visual update. That distinction matters because browsers can slow background tabs to save power: the display may update later, but when it updates the remaining time is calculated from the real end timestamp. A running or paused timer is also restored from local storage after a refresh.',
      },
    ],
    faq: [
      {
        q: 'What is the standard Pomodoro timer setting?',
        a: 'A common starting pattern is 25 minutes of focus, a 5-minute short break, and a 15-minute long break after every four completed focus sessions. You can change all four values before starting this timer.',
      },
      {
        q: 'Does the Pomodoro timer keep my task list and session log private?',
        a: 'Yes. Tasks, timer state and the newest 100 completed focus-session records are saved only in this browser’s local storage. This tool does not require an account or send those entries to a server.',
      },
      {
        q: 'Will the timer stay accurate in a background tab?',
        a: 'Yes. The remaining time is calculated from the saved end timestamp rather than from display ticks, so a slowed background tab does not add extra time when you return.',
      },
      {
        q: 'How do browser notifications work?',
        a: 'Turn on Browser notifications and approve your browser’s permission prompt. The browser can then show a completion alert when an interval ends while the page remains open; sound is available after you start a session.',
      },
      {
        q: 'Which keyboard shortcuts can I use?',
        a: 'Space starts or pauses the current interval, R resets it to its full duration, and S skips to the next prepared interval. These shortcuts do not run while you are typing in an input field.',
      },
    ],
    ui: uiEn,
  },
  ko: {
    title: '뽀모도로 타이머 — 할 일·세션 기록·알림',
    description:
      '할 일 목록, 집중 세션 기록, 선택형 브라우저 알림을 갖춘 무료 뽀모도로 타이머입니다. 가입과 광고 없이 모든 기록을 이 브라우저에만 저장합니다.',
    h1: '뽀모도로 타이머',
    tagline: '할 일 하나를 골라 집중하고, 이 브라우저에만 남는 세션 기록과 선택형 알림을 사용합니다.',
    name: '뽀모도로',
    keywords: ['뽀모도로', '뽀모도로 타이머', '공부 타이머', '집중 타이머', '25분 타이머', 'pomodoro timer'],
    howTo: [
      '집중할 일을 추가한 뒤 동그란 선택 버튼으로 하나를 고릅니다.',
      '시작 버튼 또는 스페이스바를 눌러 기본 25분 집중 세션을 시작합니다.',
      '집중 세션이 끝나면 준비된 5분 휴식을 하고, 네 번째 집중 세션 뒤에는 15분 긴 휴식을 합니다.',
      '다른 시간 구성이 필요하면 시작 전에 세션 설정에서 집중 시간과 반복 횟수를 바꿉니다.',
      '선택한 할 일과 연결된 집중 세션 기록을 확인합니다. 기록은 이 브라우저에만 남습니다.',
    ],
    sections: [
      {
        heading: '기본 뽀모도로는 25분 집중, 5분 휴식입니다',
        body: '가장 널리 쓰이는 뽀모도로 구성은 25분 집중 뒤 5분 휴식입니다. 집중 세션을 네 번 마치면 더 긴 휴식을 하는 방식이며, 15분을 시작값으로 많이 사용합니다. 다만 이 시간은 생산성을 측정하는 공식 규격이 아니므로 자신의 과제와 집중 시간에 맞게 조절하는 것이 좋습니다. 이 타이머에서는 집중·짧은 휴식·긴 휴식을 각각 1~180분으로, 긴 휴식 전 집중 횟수를 1~12회로 설정할 수 있습니다. 설정을 바꾸면 진행 중인 카운트다운은 초기화됩니다.',
      },
      {
        heading: '완료한 집중 세션은 이 기기에만 기록됩니다',
        body: '집중 세션이 끝나면 완료 시각과 선택한 할 일 이름을 이 브라우저의 로컬 저장소에 기록합니다. 가장 최근 집중 세션 100개만 보관하고, 오늘 횟수는 기기에서 설정한 현지 날짜를 기준으로 셉니다. 이 기록을 위해 계정을 만들거나 서버에 요청을 보내지 않으며, 제3자 추적기도 사용하지 않습니다. 사이트 데이터를 지우거나 다른 브라우저를 사용하면 기록은 삭제되거나 서로 분리됩니다.',
      },
      {
        heading: '백그라운드 탭에서도 카운트다운이 밀리지 않는 방식',
        body: '이 타이머는 화면이 갱신될 때마다 1초를 빼는 대신, 세션이 끝날 시각을 저장한 뒤 현재 시각과 비교해 남은 시간을 계산합니다. 브라우저는 배터리를 아끼기 위해 백그라운드 탭의 화면 갱신을 늦출 수 있지만, 화면이 다시 갱신될 때 실제 종료 시각으로 계산하므로 시간이 더해지지 않습니다. 실행 중이거나 일시정지한 타이머는 로컬 저장소에 보관해 새로고침 뒤에도 복원합니다.',
      },
    ],
    faq: [
      {
        q: '기본 뽀모도로 시간은 어떻게 되나요?',
        a: '보통 25분 집중, 5분 짧은 휴식, 집중 4회 뒤 15분 긴 휴식으로 시작합니다. 이 타이머에서는 시작 전에 네 가지 값을 모두 바꿀 수 있습니다.',
      },
      {
        q: '할 일 목록과 세션 기록은 외부로 전송되나요?',
        a: '아니요. 할 일, 타이머 상태, 최근 완료한 집중 세션 100개는 이 브라우저의 로컬 저장소에만 보관합니다. 계정이 필요 없고 서버로 전송하지 않습니다.',
      },
      {
        q: '다른 탭으로 이동해도 시간이 정확한가요?',
        a: '네. 화면 갱신 횟수가 아니라 저장된 종료 시각을 기준으로 남은 시간을 계산하므로 백그라운드 탭이 느려져도 돌아왔을 때 시간이 더해지지 않습니다.',
      },
      {
        q: '브라우저 알림은 어떻게 켜나요?',
        a: '브라우저 알림 스위치를 켠 뒤 브라우저의 권한 요청을 허용하면 됩니다. 페이지가 열려 있는 동안 세션이 끝날 때 완료 알림을 볼 수 있으며, 소리는 세션을 시작한 뒤 사용할 수 있습니다.',
      },
      {
        q: '키보드 단축키는 무엇인가요?',
        a: '스페이스바는 시작·일시정지, R은 현재 세션 초기화, S는 다음 세션으로 건너뛰기입니다. 입력칸에 글자를 쓰는 동안에는 단축키가 작동하지 않습니다.',
      },
    ],
    ui: {
      focus: '집중',
      shortBreak: '짧은 휴식',
      longBreak: '긴 휴식',
      phase: '세션 종류',
      start: '시작',
      pause: '일시정지',
      resume: '계속',
      reset: '초기화',
      skip: '건너뛰기',
      completed: '세션이 끝났습니다. 다음 세션을 시작할 수 있습니다.',
      tasks: '할 일 목록',
      tasksHint: '집중을 시작하기 전에 할 일 하나를 고릅니다.',
      taskPlaceholder: '무엇에 집중할까요?',
      addTask: '추가',
      noTasks: '할 일을 추가하면 완료한 집중 세션에 함께 기록합니다.',
      selectTask: '{task} 선택',
      select: '선택',
      selected: '선택됨',
      done: '완료',
      reopen: '다시 열기',
      removeTask: '{task} 삭제',
      remove: '삭제',
      today: '오늘 집중 세션',
      round: '다음 집중 회차',
      notifications: '브라우저 알림',
      notificationHint: '스위치를 켤 때만 브라우저가 알림 권한을 요청합니다.',
      notificationTitle: '뽀모도로 타이머',
      notificationBody: '세션이 끝났습니다. 다음 세션: {phase}.',
      settings: '세션 설정',
      settingsHint: '설정을 바꾸면 현재 타이머가 초기화됩니다.',
      focusMinutes: '집중(분)',
      shortBreakMinutes: '짧은 휴식(분)',
      longBreakMinutes: '긴 휴식(분)',
      rounds: '긴 휴식 전 집중 횟수',
      sessionLog: '집중 세션 기록',
      sessionLogHint: '완료한 최근 집중 세션 100개를 이 브라우저에만 저장합니다.',
      noSessions: '집중 세션을 완료하면 첫 기록이 추가됩니다.',
      untitledTask: '이름 없는 집중 세션',
      startPause: '시작 / 일시정지',
    },
  },
};
